services:
  teststoreapp.webapp:
    image: ${DOCKER_REGISTRY-}teststoreappwebapp
    build:
      context: ./TestStoreApp.WebApp
      dockerfile: Dockerfile
    depends_on:
      - teststoreapp.api.products

  teststoreapp.api.products:
    image: ${DOCKER_REGISTRY-}teststoreappapiproducts
    build:
      context: ./Api/TestStoreApp.Api.Products
      dockerfile: Dockerfile
